#!/usr/bin/env bash

# Yandex Cloud: 'Text to speach', tts.
r=`tput setaf 1`
g=`tput setaf 2`
rs=`tput sgr0`

function help(){
    echo "${g}Usage:${rs}: "
    echo "echo 'Text' | tts [options] > output.mp3"
    echo "${g}Options:${rs}"
    echo '[-s jane|oksana|alyss|omazh|zahar|ermil]'
    echo '[-e good|neutral|evil]'

}

SPEAKER='speaker=zahar'
EMOTION='emotion=good'

# https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f
PARAMS=""

while (( "$#" )); do
  case "$1" in
    -h|--help)
        help
        exit 0
      ;;
      -s|--speaker)
        SPEAKER="speaker=$2"
        shift 2
      ;;
       -e|--emotion)
        EMOTION="emotion=$2"
        shift 2
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "$PARAMS"


KEY=$YANDEX_CLOUD_TTS_KEY
TEXT=$( cat "${1:-/dev/stdin}")
FILE="/dev/stdout"

curl "https://tts.voicetech.yandex.net/generate?format=mp3&lang=en-US&$SPEAKER&$EMOTION&key=$KEY" -G --data-urlencode "text=$TEXT" > "$FILE"
