#!/usr/bin/env bash

# Yandex Cloud: 'Text to speach', tts.

r=`tput setaf 1`
g=`tput setaf 2`
rs=`tput sgr0`

function help(){
    echo "${g}Usage:${rs}"
    echo "Piplene: "
    echo "echo 'Text' | tts [options] > output.mp3"
    echo "Args: "
    echo "tts [options] -- <text_to_read> <output_file>"
    echo "${g}Options:${rs}"
    echo '[-s jane|oksana|alyss|omazh|zahar|ermil]'
    echo '[-e good|neutral|evil]'
    echo '[-k <yandex_cloud_key>]'
    echo '[-i <Path_to_File_with_yandex_cloud_key>]'
    echo '[-S <from 0.1 to 3.0, normal 1>] This is a text reading speed.'
}

SPEAKER='speaker=zahar'
EMOTION='emotion=good'
SPEED='speed=1.0'
KEY=$YANDEX_CLOUD_TTS_KEY
FILE=
TEXT=

# https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f 
# Code from this source has problem when aprsing quotes strings in 
# positional arguments.
PARAMS=""
while (( "$#" )); do
  case "$1" in
    -h|--help)
        help
        exit 0
      ;;
      -s|--speaker)
        SPEAKER="speaker=$2"
        shift 2
      ;;
      -S)
        SPEED="speed=$2"
        shift 2
      ;;
       -e|--emotion)
        EMOTION="emotion=$2"
        shift 2
      ;;
     -k|--key)
        KEY="$2"
        shift 2
      ;;
      -i)
        KEY=$( cat "$2")
        shift 2
      ;;
    --) # end argument parsing
      shift
      echo "I'm here"
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;

  esac
done



# Select use Params or Stdin/Stdout for input/ouput.
if [ -n "$1" ]; then
  TEXT="$1"
  echo $TEXT
else
  TEXT=$(cat /dev/stdin)
fi
if [ -n "$2" ]; then
  FILE="$2"
  echo $FILE
else
  FILE="/dev/stdout" 
fi

curl "https://tts.voicetech.yandex.net/generate?format=mp3&lang=en-US&$SPEAKER&$SPEED&$EMOTION&key=$KEY" -G --data-urlencode "text=$TEXT" > "$FILE"
