#!/usr/bin/env bash

# Yandex Cloud: 'Text to speach', tts.

function help(){
    echo "this is help"

}

SPEAKER='speaker=zahar'
EMOTION='emotion=good'

# https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f
PARAMS=""

while (( "$#" )); do
  case "$1" in
    -h|--help)
        help
        exit 0
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "$PARAMS"


KEY=$YANDEX_CLOUD_TTS_KEY
TEXT=$( cat "${1:-/dev/stdin}")
FILE="/dev/stdout"

curl "https://tts.voicetech.yandex.net/generate?format=mp3&lang=en-US&$SPEAKER&$EMOTION&key=$KEY" -G --data-urlencode "text=$TEXT" > "$FILE"
